

spring:
    application:
        name: demo-cloud-gateway-resource
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9000
server:
    port: 8081
